steps:
  - name: 'bash'
    args:
      - -c
      - cp -r workers/ models/ worker_a/

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - Worker_A
      - --region=${_REGION}
      - --source=worker_a/
      - --entry-point=process_routed_request
      - --trigger-http
      - --runtime=python313
      - --min-instances=10
      - --max-instances=10
      - --concurrency=1
      - --service-account=adaptimould-worker-account@${_PROJECT_ID}.iam.gserviceaccount.com
      - --set-env-vars=PROJECT_ID=${_PROJECT_ID}
      - --set-env-vars=PUBLISHER_SUCCESS_TOPIC_ID=worker-success-topic
      - --set-env-vars=PUBLISHER_ERROR_TOPIC_ID=message-error-topic
      - --set-env-vars=DELAY=0

substitutions:
  _PROJECT_ID: your-project-id
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY