steps:
  - name: 'bash'
    args:
    - -c
    - cp -r utils/ models/ metrics_processor/

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - Metrics_Processor
      - --region={_REGION}
      - --source=metrics_processor/
      - --entry-point=update_metrics
      - --trigger-topic=worker-success-topic
      - --runtime=python313
      - --service-account=adaptimould-metrics-account@{_PROJECT_ID}.iam.gserviceaccount.com
      - --set-env-vars=DATABASE_ID=adaptimould-firestore
      - --set-env-vars=PROJECT_ID={_PROJECT_ID}

substitutions:
  _PROJECT_ID: your-project-id
  _REGION: us-central1

options:
  logging: CLOUD_LOGGING_ONLY